ProtonMail/react-components

containers/payments/usePayment.js

In package.json (and everywhere else), the package name is react (no capitalization)

remove capitalization: import ... React

---

components/button/Button.js

Today: 
`<Button className="mlauto">-></Button>` = :boom: no more styles :/
With the fix:
It works.
btw we should not have mr1 inside the button imho

[Button] - Allow us to extend classNames

---

components/icon/Icon.js
components/toggle/Toggle.js

`<Icon className="ml1" />` didn't work.
New props:
- `fill`: default value **grey** -> fill color for the icon
- `size`: default value **16** -> size of the icon

Easier to extend classNames for the Icon

---

components/input/ColorPicker.js

Two new changes:
- I changed the prop name onColorChange to onChange since that is the common notation everywhere else. Also this prop is now passed down to ChromePicker so that we can control what happens with color changes from parent components.
- The useEffect hook is triggered by changes in the prop initialRgbaColor. In this way we can also change the color of the color picker from parent components.

Improvements to Color Picker

---

containers/themes/ThemeCard.js
containers/themes/availableThemes.js

https://ttag.js.org/docs/tag-gettext.html#invalid
Moved translation of theme labels into proton-shared.
Related PR in `proton-shared`: https://github.com/ProtonMail/proton-shared/pull/18

Remove invalid translations for theme labels

---

components/autocomplete/useAutocomplete.js
components/autocomplete/useAutocomplete.test.js

proton-shared PR for identity function: https://github.com/ProtonMail/proton-shared/pull/24
Initial idea was that if you wanted to keep track of selected/removed events in components using autocomplete hook, you would just create custom functions like:
```
const handleSelect = (item, label) => {
select(item, label);
// your stuff
}
```
But this way you don't yet have access to updated selectedItems list, because it's going to be updated after the next render/state update, so you'd end upt needing to reimplement the whole select function from hook. Solved this by adding an effect, that will call onChange after selectedItems changes.
```
const {...} = useAutocomplete({
onChange: (selectedItems) => {
// your stuff using updated selectedItems
}
})
```

Add ability to bind onChange to autocomplete hook

---

containers/addresses/AddressesSection.js
containers/domains/DomainsSection.js
containers/members/MembersSection.js
containers/payments/subscription/helpers.js

Fixes several errors:
- plurals need `msgid` as as a first parameter: https://c-3po.js.org/reference-ngettext.html#usage
- nggettext throws errors when string parameters are not template literals, so fixed that
- added missing contexts

Fix i18n errors

---

components/pagination/usePagination.js

When list gets shorter, i.e. after filtering, page stays the same, and can go out of pagination range. 
Added effect to set page to the last one if page went out of range.

Set pagination to last page if page is out of range after list changes

---

components/input/Input.js
containers/invoices/InvoiceState.js
containers/invoices/InvoiceType.js

Backend model has more invoice types and states than we have defined: https://gitlab.protontech.ch/ProtonMail/Slim-API/blob/develop/app/Models/Invoice.php
Related PR: https://github.com/ProtonMail/proton-shared/pull/27
Also input component forwarded some unexpected properties to the element which threw warnings in console.

Add missing invoice types and fix input warnings

---

containers/login/LoginForm.js
containers/login/TOTPForm.js
containers/login/UnlockForm.js

**Summary**
Some of the components don't have unique attributes. Without them, the e2e tests will end up with weird selectors and code that's hard to understand. 
This pr follows the [cypress best practices](https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements) and adds data-cy-* attributes to the elements in the login form.

Add data-cy-* attributes to the elements in the login form.

---

components/dropdown/DropdownMenu.js
containers/login/LoginForm.js

There is no reason for dropdown menu to allow null children. It causes errors when trying to access `.key` property for it, and null is useful when removing dropdown buttons from the menu based on some conditions.
Fixed login button widths which has been bothering me every time I see login form :)

Ignore null from dropdown menu children and fix login input widths

---

components/input/FileInput.js
containers/keys/shared/SelectKeyFiles.js

In order to allow FileInput to accept the same file twice we need to reset it by hand. Such a manual reset was done in external components before (see https://github.com/ProtonMail/react-components/blob/master/containers/keys/shared/SelectKeyFiles.js#L13), but we can move it inside the component.

Small fix to FileInput

---

containers/addresses/AddressModal.js
containers/addresses/useAddressModal.js

Simply removes signature field. https://github.com/ProtonMail/protonmail-settings/issues/49

Remove signature field in address create modal

---

containers/autoReply/AutoReplyForm/fields/EndDateField.js
containers/autoReply/AutoReplyForm/fields/StartDateField.js
containers/autoReply/AutoReplyForm/useAutoReplyForm.js
containers/autoReply/AutoReplyTemplate.js
containers/autoReply/utils.js

Dates were saved in locale timezone, not the one specified. Went over the whole error handling and refactored it.
Fixes: https://github.com/ProtonMail/protonmail-settings/issues/74

Fix auto-reply date handling

---

components/container/ObserverSection.js

I noticed there was a small bug in the ObserverSections component when working in combination with the subsidebar. It seems when clicking on one of the links of the subside bar for a certain `id`, the intersection ratio for section `id` does not happen to be `1`, but instead a number close to it like `0.998...`. If a small section below `id`, say `id2`, happens to have an intersection ratio equal to `1`, the url displayed will be `...#id2` after clicking the link on the subsidebar for `id`, which is obviously not nice.
By rounding to two decimal places the intersection ratios, the bug goes away.
Requires https://github.com/ProtonMail/proton-shared/pull/32

Fix for small bug in ObserverSections component

---

containers/api/ApiProvider.js
containers/api/Captcha.js
containers/api/HumanVerificationModal.js

- The API is not yet ready.
Fix https://github.com/ProtonMail/react-components/issues/130

Add human verification support on all routes

---

babel.config.js
components/input/RadioGroup.js
containers/userVPN/Provider.js
containers/userVPN/index.js
containers/userVPN/useUserVPN.js
containers/userVPN/userVPNContext.js
containers/vpn/OpenVPNConfigurationSection/ConfigsTable.js
containers/vpn/OpenVPNConfigurationSection/Country.js
containers/vpn/OpenVPNConfigurationSection/LoadIndicator.js
containers/vpn/OpenVPNConfigurationSection/OpenVPNConfigurationSection.js
containers/vpn/OpenVPNConfigurationSection/ServerConfigs.js
containers/vpn/OpenVPNConfigurationSection/utils.js
containers/vpn/ProtonVPNClientsSection/ProtonVPNClientsSection.js
containers/vpn/ProtonVPNClientsSection/VPNClientCard.js
helpers/countries.js
hooks/useSortedList.js
hooks/useSortedList.test.js
index.js
package.json

Adds:
- Necessary sections for downloads page
- `useSortedList` hook to simplify sorting lists in components
- user vpn info provider - this one I would like some feedback on, would it make sense to always load this data in VPN project?
CI is failing because of a merge required in proton-shared first.

ProtonVPN Downloads page sections

---

containers/illustration/IllustrationPlaceholder.js

With `text=''`, if `text` was not specified, the component would display a useless `<p></p>`

Remove wrong default prop in IllustrationPlaceholder

---

containers/autoReply/AutoReplyTemplate.js

Related to this issue: https://github.com/ProtonMail/protonmail-settings/issues/41
- applied `.cut` class to message container, which makes a basic hyphenation of text (class has been updated on Design System here https://github.com/ProtonMail/design-system/commit/266b993731dd545c7592f92f10334af12dd1d757 )
Chrome with no support of `hyphens` (PC mostly):
Firefox (supports `hyphens` property, but of course which this test, hyphen dictionnaries go crazy 🎉  ):

Fix autoreply long message display

---

containers/account/TwoFactorSection.js

Related to: https://github.com/ProtonMail/protonmail-settings/issues/102
- Fixed link:

Fix 2FA help link

---

components/orderableTable/OrderableTableRow.js
containers/labels/LabelSortableItem.js
containers/labels/LabelSortableList.js

Related to this: https://github.com/ProtonMail/protonmail-settings/issues/57 
- Remove column widths for notifications/actions 
(snap at 150% zoom, click on image to have real display)
Bonus:
- Also fixed vertical alignment of labels/folders/"grab" icon
- Added helper class for cursor instead of inline-styles

Fix orderableTableDisplay component

---

components/popper/utils.js
components/popper/utils.test.js

`design-system`: https://github.com/ProtonMail/design-system/pull/190/files
TIL: `array.sort` works differently in node and browser.
Adds support for `left-bottom`, `left-top`, `right-top`, `right-bottom` placements. And fixes how positions are determined.
As needed for:
Wrote tests for the most important placements, might finish tests for all positions later.

Add missing four placements and fix sorting

---

components/logo/MainLogo.js
containers/app/AppsSidebar.js
containers/heading/SupportDropdown.js
containers/heading/UserDropdown.js
containers/payments/BillingSection.js
containers/payments/Bitcoin.js
containers/payments/Cash.js
containers/payments/CreditsModal.js
containers/payments/subscription/SubscriptionModal.js
containers/payments/subscription/SubscriptionSection.js
containers/support/BugModal.js

Since [this change](https://github.com/ProtonMail/proton-pack/commit/3b3a42a51027ffc681a7f4f366e678cff1b50260), the app name is defined in `useConfig` hook. So we don't need to define `currentApp` prop to identify the app context.
Fix https://github.com/ProtonMail/protonvpn-settings/issues/42
Fix https://github.com/ProtonMail/protonvpn-settings/issues/43
Fix https://github.com/ProtonMail/protonvpn-settings/issues/44

Remove currentApp prop and use APP_NAME from useConfig

---

containers/account/UsernameSection.js

Before :
After fix:
Added helper to get correct alignment.

Fix Username Section alignment

---

containers/vpn/OpenVPNAccountSection/OpenVPNAccountSection.js

Fields and buttons related to them were not "spaced" correctly (related things must be close, proximity law = Gestalt laws of grouping)
Used margin helpers.
Before:
After:

Fix spacing between Open VPN fields/buttons

---

containers/vpn/ProtonVPNClientsSection/VPNClientCard.js

Fixed some HTML issues on VPN client card component:
- a `button` in a link, no => better applying `pm-button` style to link directly
- added `increase-surface-click` to link and `relative` to block, so the full block is clickable
- added `sr-only` `span` element in link, in order for the links to be vocalized "Download Android", "Download iOS", etc. instead of "download, download, etc."
No visual change:

Fix VPNClientCard component

---

components/dropdown/DropdownButton.js

The caret was badly positionned:
An empty `span` with `mr0-5` was causing this.
- Fixed it by updating the condition
Snap:

Fix DropDownButton alignment

---

containers/addresses/AddressesWithMembers.js
containers/apps/ProtonMailAppsSection.js
containers/domains/DomainsTable.js
containers/invoices/InvoicesSection.js
containers/keys/KeysTable.js
containers/keys/reactivateKeys/ReactivateKeysList.js
containers/members/MembersSection.js
containers/paymentMethods/PaymentMethodsTable.js
containers/vpn/OpenVPNConfigurationSection/ConfigsTable.js

Related to this: https://github.com/ProtonMail/protonmail-settings/issues/108
Design requested that tables with the last column that are containing "action" buttons have this column right-aligned.
Modifier `pm-simple-table--has-actions` for `table` tag has been created in Design System to manage this: https://github.com/ProtonMail/design-system/commit/7e9830669a7e9d23229484d6b13d23c61cbea478
It has been applied to all concerned `table`s.
Example with fix applied:
Fixes: https://github.com/ProtonMail/protonmail-settings/issues/108

Update tables with last "action" column

---

components/link/Info.js

In order to have info colored with primary project color => Updated `fill` class to `fill-primary`.
For ProtonVPN settings, it gives this:

Fix info fillColor (primary)

---

components/sidebar/NavItem.js

The class for icon in navigation was not correct, updated it to `navigation__icon`.
Before:
After fix:

Fix navigation icon class

---

components/input/Radio.js

The problem comes from the class `inline-flex` applied by default on `<radio` component. In this special case, it should not be present.
- `inline-flex` class will be added by default is no class is specified
Fix https://github.com/ProtonMail/react-components/issues/220 
Fix https://github.com/ProtonMail/react-components/issues/229

Fix card display

---

containers/addresses/IdentitySection.js

The signature block was not truncating properly its content:
- added `cut` class (hyphenation)
After:

Add hyphenation class to signature block

---

containers/domains/CatchAllModal.js

Catch-all was too small for its contents.
- Used standard modal (removed `small`)

Fix catch-all modal

---

components/alert/Alert.js

Spotted by @emnproton :
> I think the description text that appears under headings should be more narrow on large resolution displays, as that makes the text more readable.
- Based on UX recommendations, I've added a helper `mw70ch` (70 caracters), which will avoid too long lines
After:

Fix alert block max width

---

components/icon/Icon.js
components/text/ErrorZone.js

* Added `rotate` property to `<Icon />` component.
* Added className property to `<ErrorZone />` component.
* Made `id` property not required for `<ErrorZone />` component.
* Added `<RedeemCouponSection />` container.
For https://github.com/ProtonMail/proton-vpn-settings/issues/81

Redeem page

---

containers/vpn/OpenVPNConfigurationSection/ConfigsTable.js
containers/vpn/OpenVPNConfigurationSection/LoadIndicator.js

Some small adaptations for mobile:
- hide status
- removed inline-styles
- made column have auto width on mobile

Fix - rwd display of secure core table

---

containers/account/EnableTwoFactorModal.js

Fix https://github.com/ProtonMail/proton-vpn-settings/issues/127
This would change it from:
* A user without any addresses ~~`ProtonMail (bdtst@protonmail.com)`~~ to **`Proton (bdst)`**
* A user with addresses: ~~`ProtonMail (username@protonmail.com)`~~ to **`Proton (username@protonmail.com)`**

Change issuer to Proton and remove @protonmail

---

containers/vpn/OpenVPNConfigurationSection/OpenVPNConfigurationSection.js

Fixes free user not being able to bulk download server configs. Backend will fix the error where free user is able to download basic configs as well.

Enable download all server configs for free users

---

containers/vpn/OpenVPNAccountSection/OpenVPNAccountSection.js
containers/vpn/OpenVPNAccountSection/OpenVPNCredentialsModal.js

Update OpenVPN structure to use a modal when we want to edit credentials.
Fix https://github.com/ProtonMail/proton-vpn-settings/issues/100

Review OpenVPN section to use a modal

---

components/input/PasswordInput.js

I've changed a bit the password revealer styles to avoid problems with password managers.
- added class `mauto` on icon

Fix aligment of icon

---

components/input/PasswordInput.js

- just added `flex-item-noshrink` on the button for responsive display.

Fix button revealer (noshrink)

---

containers/payments/Payment.js

In order to achieve design for VPN signup, I had to add a property fluidDisplay on payment component, if it is "activated", it adds some classes on the field container.
if this is not activated, we have standard behaviour:

Feat - add option to make payment block fluid

---

containers/heading/UserDropdownButton.js

- Added vertical centering `flex-items-center` class on button
Fixes: https://github.com/ProtonMail/proton-vpn-settings/issues/201

Fix vertical centering of user Drop down

---

components/loader/Loader.js

- centered loader using `flex` and `mauto` 
Fixes: #276

Fix #276 - loader centering

---

components/logo/MailLogo.js
components/logo/MainLogo.js
components/sidebar/Sidebar.js

Spotted by design team: the logo was not properly aligned (vertically)
- Added a `flex` helper to center it
- Wrapped "mobile" logo in sidebar in a div (to avoid a conflict between `flex` and `nodesktop/notablet` helpers)
- Added a modifier when plan is empty, in order to apply correct height (to center vertically correctly, otherwise the plan is a bit too high)
Snapshots: (I've zoomed to show the vertical centering)
With plan:
Without:

Fix logo alignment

---

components/autocomplete/Autocomplete.js
components/autocomplete/Autocomplete.test.js

BEFORE:
pre-filled values bug:
minChars=0 bug (known in awesomplete, did a workaround for us):
fixed both:

Make minChars=0 work intuitively and fix autocompletes with pre-filled values

---

containers/heading/SupportDropdownButton.js

Spotted by design: the caret of the support dropdown button did not have the correct color on hover.
- fixed by adding `topnav-icon` class on it

Fix - support drop down caret color on hover

---

components/logo/MainLogo.js
containers/app/LoaderPage.js
containers/heading/SupportDropdown.js
containers/heading/SupportDropdownButton.js
containers/heading/UserDropdown.js
containers/login/ForgotUsernameContainer.js
containers/login/PublicHeader.js
containers/login/ResetPasswordContainer.js
containers/login/SignInLayout.js
containers/paymentMethods/PaymentMethodsSection.js
containers/payments/Bitcoin.js
containers/payments/Cash.js
containers/payments/CreditsModal.js
containers/payments/subscription/PaymentDetails.js
containers/payments/subscription/SubscriptionModal.js
containers/support/BugModal.js
index.js

Allow us to use similar screens for ProtonMail implementations
Details:
- Extract SignInLayout
- Extract ResetPasswordContainer
- Extract ForgotUsernameContainer
- Review PublicHeader
- Review SupportDropdown to support auth/unauth
- Use CLIENT_TYPE instead of APP_NAME

Extract login screens

---

containers/login/FooterDetails.js
containers/payments/PayPal.js
containers/payments/PaymentVerificationModal.js
containers/payments/paymentTokenHelper.js

Use `ReturnHost` value returned by API to compare origin.
```json
{
"Code": 1000,
"Token": "mLN7SpUGz25ol1X5wDoDGOGG",
"Status": 0,
"ApprovalURL": "https://hooks.stripe.com/3d_secure_2/hosted?publishable_key=pk_test_FgIybmWSP4xgpBTsUJMFYG1k&setup_intent=seti_1FNGJZKpW9DKy5hnIiHwWvlZ&setup_intent_client_secret=seti_1FNGJZKpW9DKy5hnIiHwWvlZ_secret_Ft2OrbowBdg1WtE7aOOJuRxuMiuh00c&source=src_1FNGJZKpW9DKy5hn7lwfDVIq",
"ReturnHost": "protonmail.blue/api"
}
```

Use ReturnHost value returned by API to compare origin

---

containers/resetPassword/DangerVerificationForm.js

Fixes https://github.com/ProtonMail/proton-vpn-settings/issues/294
Note:
I couldn't test it, as google captcha verification fails at server side every time I pass it on localhost.

Add validation error when user misstypes DANGER

---

containers/sidebar/StorageSpaceStatus.js

Right now the rounding in the storage selector does not give a percentage, but rather 0 or 1. I'm rounding to 0.01 precision here (so that percentages displayed are things like 32.44%, 0.12%, etc). But if we want to round just to an integer, simply do
```
Math.round((UsedSpace / MaxSpace) * 100)
```
Fixes https://github.com/ProtonMail/proton-contacts/issues/174

Round to 0.01 precision in the storage selector

---

components/modal/Confirm.js

`confirm` and `cancel` should have the same propTypes as `submit` and `cancel` in `FormModal`

Add proptypes to confirm modal

---

styles/index.scss

I'm working on the Design system to split `global-structure` into several components.
Merge this one only when Design system will be ready. :)

Fix - add new fragments from Design system

---

components/link/Info.js

It's useful to be able to change the button class for component, for example in table headers `inline-flex` doesn't align properly (should have `vertical-align: middle`, which is default for button).
Passing: `<Info buttonClass="ml0-25">...` in table headers now will align the button properly.

Add button class to info component

---

containers/payments/PayPal.js

Add support for `paypal-credit` as payment method for all cases except `update` (when we update a payment method).

Handle paypal-credit as payment method

---

containers/payments/PayPal.js

Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/20

Align `click here` link with the rest of the text

---

containers/search/Searchbox.js

The input displayed in the Searchbox sometimes needs to be modified by external components (like in case of having to clear it). The simplest solution is to use a `useEffect` hook. Although it's ugly, notice that we are already using a similar structure in the `SearchInput` component

Modify Searchbox so that it can be cleared from the outside

---

containers/notification/EmailModal.js

- used standard modal (not `mini` one)

Fix - recovery email modal width

---

components/sidebar/MobileNavServices.js
hooks/useActiveBreakpoint.js

It's convenient to have it return Booleans `isMobile`, `isTablet` and `isDesktop` apart from the breakpoint itself

Modify useActiveBreakpoints hook

---

components/dropdown/DropdownButton.js

Sometimes a warning was being thrown in the console because the prop `loading` was passed to `<button>` throught the `DropdownButton` component.

Fix warning in DropdownButton

---

containers/organization/OrganizationSection.js

Hotfix - typo organisation

---

containers/search/SearchSection.js

The new design require to have the text "Require exact match" for the toggle in `Settings > General > Search` instead of the v3 "Do not require exact match". We simply need to use the opposite values in this toggle. The corresponding PR fix in `mail` is awaiting review
Closes https://github.com/ProtonMail/proton-mail-settings/issues/191

Change wildcard toggle condition and text

---

containers/payments/subscription/helpers.js

Fix https://github.com/ProtonMail/proton-mail-settings/issues/193
Translations fail because the singular version doesn't include the variable. It works in the native language because it's a pure JS variable interpolation but for other language, the ttag has to do the interpolation but doesn't know about the variable.

Change subscriptions option message ids to fix the variable

---

containers/keys/KeysTable.js

Fix https://github.com/ProtonMail/proton-mail-settings/issues/202
Tooltip is not good in this case because it doesn't allow to select the fingerprint. In addition, the tooltip default size is not large enough to show the fingerprint.
So I propose a native HTML title and a copy button.

Show fingerprints in title and add a copy button

---

containers/addresses/AddressesSection.js

To add a new address, you need to be a paid user to create `protonmail.com`, `protonmail.ch`, `pm.me` or custom domain addresses; and this can be done only on the main account.
Fix https://github.com/ProtonMail/proton-mail-settings/issues/205

No need to have multiple member to add a new address

---

containers/addresses/AddressModal.js
containers/addresses/DomainsSelect.js
hooks/usePremiumDomains.js
index.ts

- catch if new address is Name@pm.me
- add usePremiumDomains hook
- use usePremiumDomains hook in DomainsSelect
Fix https://github.com/ProtonMail/proton-mail-settings/issues/206

Catch pm.me address creation to display proper error

---

components/image/RemoteImage.js

I need to use different text than `Load image` in `contacts` (https://github.com/ProtonMail/proton-contacts/issues/231) when using the `RemoteImage` component.

Allow to change the text in the RemoteImage component

---

containers/filters/editor/Name.js

Fix https://github.com/ProtonMail/proton-mail-settings/issues/182
There is an internal validation mechanism inside the `Input` component. I think this was not intended here as there is an other one in the component.
Also, the label was referring to a username which should be a bad copy paste, I replaced it by "filter name".

Fix filter name validation

---

containers/filters/editor/Sieve.js

Fix https://github.com/ProtonMail/proton-mail-settings/issues/214
This is a tricky bug inside codemirror. The selection is done by measuring and simulating the code area.
Perhaps due to the modal appearance animation, the initial measures are corrupted. Any refresh after that fix the problem. Any edition of the code does too.
The problem was: when to trigger a render? I did not found any good events to connect to. I never recommand to use setTimeout but I did not found anything else here.
"Theoretically" the measure issue is due to CSS annimation so the time is not directly dependant on the user computer performance so it "should" be stable.
Edit: the exact timing is 200ms, I used 300 to be secure.

Fix SIEVE editor by delaying content

---

containers/vpn/OpenVPNAccountSection/OpenVPNCredentialsModal.js

Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/23

Make `guest` a reserved word that can't be used for OpenVPN credentials.

---

components/link/Info.js

Fix https://github.com/ProtonMail/proton-mail-settings/issues/215
We've got an `button` (from Info) in a `label`. On Safari only, it appears that clicking the button trigger the label, then the input associated. Calling `event.preventDefault()` prevents it (Not `event.stopPropagation()`).

Fix click behaviour on the info bubble on Safari

---

containers/filters/ActionsFilterToolbar.js
containers/filters/AddFilterModal.js

Fix https://github.com/ProtonMail/proton-mail-settings/issues/197
Handle request failure in filter creation. Close the modal and update the list.

Handle failure on add filter modal

---

containers/addresses/EditAddressModal.js

Fix https://github.com/ProtonMail/proton-mail-settings/issues/177
Intercept empty input from the reach text editor for the signatuer and replace it by a real empty string.

Handle empty signature to send real empty string

---

containers/filters/editor/Actions.js
containers/filters/editor/AutoReplyAction.js
containers/filters/editor/Conditions.js

Partially fix https://github.com/ProtonMail/proton-mail-settings/issues/218
- Trash icon only shown for 2 or more conditions
- Add move to spam and trash
- Change message for `Move to inbox`
- Add auto reply action

Improve filter edition modal, add auto reply action

---

styles/index.scss

DO NOT MERGE IT UNTIL ALL PROJECTS ARE OK !!!!!!
React component import has to be simplified, in order to allow creating project specific components and avoid using these fragments everywhere if they are not needed.
- removed some fragments
- moving these fragments to projects

Feat - better CSS import

---

containers/addresses/EditAddressModal.js

Fix https://github.com/ProtonMail/proton-mail-settings/issues/228
Sorry, that was an error in my regex. Should be stronger now.

Fix false positives on signature ending with empty lines

---

containers/filters/editor/Sieve.js

Fix https://github.com/ProtonMail/proton-mail-settings/issues/221
The PR is very simple yet I dug a bit. The problem is that we added a debounce on the lint event to save some hit to the API. But this debounce lose the return value of the lint function which codemirror use to display the eventual error.
I worked on a "promised based version of the debounce" to make it works preserving the result. But while debugging it, I discover that codemirror already has a debounce mechanism and even if there is a lot of calls, the additional debounce doesn't catch much calls (At most, one or two calls in a whole normal usage).
So clearly, this simplest solution is to remove it.
(In Angular, there is no additional debounce either)

Remove debounce on sieve lint

---

components/miniCalendar/MiniCalendar.js

(icon next and prev month are white on white...)
- fixed color in Design system
- bonus: harmonized classnames `minicalendar` and `mini-calendar` => `minicalendar`

Fix - minicalendar icons color

---

components/input/Checkbox.js

Option needed to achieve this.
- added `borderColor`

Fix - add borderColor

---

containers/filters/editor/Actions.js
containers/filters/editor/LabelActions.js

When creating a filter, adding the action Label uses the `Name` instead of the `Path`.
- Label selection is now done using the Path as a key. 
- the labelsModel.mapLabels must use the Path as key as well. This is done in PR: https://github.com/ProtonMail/proton-shared/pull/73
Fixes https://github.com/ProtonMail/proton-mail-settings/issues/240

Fix: Filter Action Label uses path instead of name

---

hooks/useApiResult.ts

Typesafe usage: `useApiResult<UserSharesResult, typeof queryUserShares>(queryUserShares, [])`
would ideally want to get rid of that typeof part, but typescript doesn't yet have existential types. At least this way we don't need to keep changing annotation when query's arguments change.

Improve useApiResult typings

---

components/sidebar/SubSidebar.js
containers/overview/IndexSection.js
containers/overview/LinkItem.js
containers/overview/Sections.js

(Almost) Fix https://github.com/ProtonMail/proton-mail-settings/issues/159
The links in the dashboard was containing the hash but in a soft navigation like this, it doesn't work.
I chose to change the link to add a manual `scrollIntoView` after the navigation.
It works pretty well unless that the scroll command is ran just after the navigation and if the page has async content, it will scroll to the position the anchor was before the data are there.
But to be honest, I don't see how it is possible to wait until the page is ready. So at least, it's better as before.

Fix settings dashboard anchor links

---

containers/payments/subscription/SubscriptionSection.js

Fix #249 - Hide "Remove coupon" button for BF coupon

---

containers/filters/editor/Actions.js
containers/filters/editor/AddConditionValue.js
containers/filters/editor/Preview.js

Fix https://github.com/ProtonMail/proton-mail-settings/issues/245
Replace the last condition value by a null value if empty.
But it need to be sanitize before sending to the API: https://github.com/ProtonMail/proton-shared/pull/79
Fix https://github.com/ProtonMail/proton-mail-settings/issues/241

Fix last empty condition value issue and move action validation

---

components/alert/DuckDuckGoAlertError.js
containers/payments/PayPal.js
containers/payments/PaymentVerificationModal.js
containers/payments/paymentTokenHelper.js
index.ts

DuckDuckGo mobile browser is not supporting [window.open](https://www.w3schools.com/jsref/met_win_open.asp) method required for our payment flow. So we have to handle this case properly for `card` and `paypal` payment methods.
- For PayPal we just display an error panel in the view.
- For card, we display the same error in the `PaymentVerificationModal` after getting the `Token` if the `Status` is not directly chargeable.
Manager: @jovanjovanovski 
Test server: https://vpnsettings.protonmail.blue (blue API)

Throw payment error for DuckDuckGo

---

containers/support/AttachScreenshot.js

Vertical alignment was not correct
- aligned buttons (add screenshot and once snapshot uploaded)

Fix - bad alignment in report modal

---

containers/search/SearchDropdown.js
containers/search/Searchbox.js

Fix https://github.com/ProtonMail/proton-contacts/issues/275
Add clear buttons on both mobile and desktop search bars.
On desktop, the cross is hidden when the search field is empty or if the advanced feature is used.

Add clear search buttons on search bars

---

styles/index.scss

Add missing fragment for custom scrollbars (which will be used on several projects)
- Add missing fragment for custom scrollbars (!) (needed for Calendar)

Fix - add custom scrollbar fragment

---

containers/sidebar/StorageSpaceStatus.js

Fixes https://github.com/ProtonMail/react-components/issues/459

Do not show upgrade storage button when on visionary or lifetime plan

---

containers/heading/SupportDropdownButton.js

Icon of support drop down was not visible. 
- added `fill-currentColor` class (the icon will be the same color as the text in the button)

Fix - support drop down icon color

---

containers/api/ApiProvider.js

Sometimes it's useful to have the whole stream instead of only reader (e.g. required for streaming decryption)

Return stream response as ReadableStream instead of Reader

---

containers/payments/PlansTable.js

Fix highlighting of table plans in dark mode.
Before:
- created a new class `pm-plans-table-row--highlighted`, styles are already added on Design system https://design-system-beta.netlify.com/table/#plans-table
- no change in light mode.

Fix - update classname for highlight cells in plan (for darkmode)

---

components/orderableTable/OrderableTable.scss

Orderable table had a white background in darkmode ^^
- fixed styles for orderable table - no update on default theme (as the CSS variable is not set, the color will use the fallback one)

Fix - orderable table CSS fix for Dark mode

---

containers/payments/BillingSection.js

- billing footer was a bit too visible in Dark mode
- used another bg helper class alias which is dark mode friendly: `bg-global-highlight` (added here https://github.com/ProtonMail/design-system/commit/901595fdd6bc8be8f0a0eb43766a9354fe6a8000 )

Fix - made billing footer dark mode friendly

---

components/container/Information.js
components/container/RelatedSettingsSection.js

Alignments of related settings blocks were not good.
- bottom-aligned button
- made blocks same height
- enhanced responsive
- fixed a point for dark mode
Desktop :
Tablets/mobile:

Fix - related settings alignments/responsive

---

containers/general/LanguageSection.js

Remove hardcoded values from the code. Now it's going to be /project with a config file generated via the CI
ex:
```json
{
"de_DE": "Deutsch",
"en_US": "English",
"es_ES": "Español",
"es_MX": "Español Mexico",
"fr_FR": "Français",
"id_ID": "bahasa Indonesia",
"it_IT": "Italiano",
"nl_NL": "Dutch",
"pl_PL": "Polski",
"pt_BR": "Português do Brasil",
"pt_PT": "Português",
"ru_RU": "Pусский"
}
``` 
- Load locale configuration via the config
Post merge, you will need to run `$ npm update proton-pack` as we need the v3.0.4 to get this config.

Read i18n config from the config

---

components/miniCalendar/MonthDays.js

Display of mini-calendar in responsive was bugged (not a circle for current day, etc.)
- wrapped buttons into a `li`s (which will be better vocalized btw), so `li` will be the grid cells
- moved `key` to `li`

Fix - mini-calendar display in responsive

---

.eslintrc.json
containers/app/AppsSidebar.js

Fix https://github.com/ProtonMail/react-components/issues/406
This PR concern only the desktop aside bar. Other PR will be linked for mobile sidebar and Angular sidebar.

Add calendar link in AppsSidebar

---

components/input/TimeInput.js

format duration as 1 hour (not 1.0 hours), 1.5 hours, 2 hours, 2.5 hours, etc

Do not use decimal for integer numbers for the duration field in the TimeInput component

---

components/miniCalendar/helper.js

When displaying 6 weeks in the mini-calendar, center the month in it

Proposal for centering months in mini-calendar

---

containers/payments/PaymentSelector.js

Fix: https://github.com/ProtonMail/proton-mail-settings/issues/256
Round the amount entered in the `other` input field to 2 digits after the floating point.
I also override the amount value in the input field on blur unless the client was paying for an amount different than what it was on screen.

Round payment amounts to 2 digits after the floating point

---

components/toolbar/ToolbarLink.tsx
index.ts

Extends the new components in #517
Usage example:
```
<Toolbar>
<ToolbarLink to="/contacts" icon="arrow-left" />
</Toolbar>
```

create ToolbarLink component

---

containers/search/Searchbox.js

While re-reading some BP in accessibility in french, I just realized that we did not follow this BP => identify the global search using `role="search"`, see https://www.accede-web.com/en/guidelines/html-css-javascript/1-structure/1-2-role-search/ 
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Search_role
- Just added `role="search"` on global search.
a11y FTW!

Fix - a11y improvement for global search

---

components/icon/RoundedIcon.js
containers/domains/DomainName.js
containers/keys/addKey/SelectEncryption.js
containers/members/MemberModal.js

Some display bugs in italian.
https://user-images.githubusercontent.com/40168570/71166265-9d4db680-2252-11ea-8292-814236c44b7b.png
Also bonus: some bugs with long domain names in domain table.
- made radio + text not wrapping
- added ellipsis
- remove some margin for mobile proper display
Fixes: https://github.com/ProtonMail/proton-mail-settings/issues/278

Fix - add user modal and domain table

---

components/toolbar/ToolbarLink.tsx
package.json

Using from other projects that have @types/react-router-dom fails builds, because reacto-components didn't have them and ToolbarLink component's typing error was not visible.
I guess this error was hidden because of allowing typescript typecheck js files recursively in tsconfig, however that's necessary until more (all?) of the projects are using typescript.
Import types to see the error in react-components
Fix the wrong types, should've been LinkProps not HtmlProps
Fixes #

Fix toolbar link types

---

components/modal/Dialog.js

Forms in small modal look like this right now:
Add the shorter label modifier to those modals:

Make small modals have a shorter label width

---

components/input/LazyRichTextEditor.js
components/input/RichTextEditor.js
containers/autoReply/AutoReplyModal.js
index.ts
styles/index.scss

The CSS for the quill editor was like 1/4 of our total css. It does not make sense to load it when loading the app, but rather "on demand" (i.e. when some component needs to use it)

Lazy load css for quill

---

containers/members/MembersSection.js

Long name in member table were not properly truncated.
- added ellipsis

Fix - username not wrapped in member table

---

components/sidebar/NavItem.js

I understand it could feal strange but in mail, menu items are links, still, if you click on the active one, I need to trigger a manual refresh so I would really need to have both link and onClick features.
Using button type in this case could work but it is semanticaly bad and it breaks the aria-current style.

Allow link NavItem to also add onClick handler

---

components/autocomplete/Autocomplete.js
components/autocomplete/Autocomplete.scss

Autocomplete in filters was not dark-mode friendly.
Made dark-mode and autocomplete speak together, and they become friends:
- used a dark-mode-friendly helper
- added a fix for text color in autocomplete input

Fix - autocomplete dark mode friendly

---

components/dropdown/Dropdown.js

Inspired by the Angular code (https://github.com/ProtonMail/Angular/blob/v4/src/app/labels/directives/dropdownLabels.js#L58), I need to lock opened my dropdown while opening a modal on top of it.
It's almost possible with the existing `autoCloseOutside` props but it needs this fix to manage the value to change in time.

Allow Dropdown props autoCloseOutside to change during components life

---

components/sidebar/Sidebar.js

Allow the scrolling to be done on the full height of the menu.
- added custom scrollbar class on navigation container (for subfolder and dark mode and etc.)

Fix - custom scroll bar in navigation
