components/button/LinkButton.js
components/button/index.js
components/toggle/Toggle.js
index.js

Add component for 
- LinkButton
Fix Toggle
- Auto checked value required
- Add mode Icon
- handleChange value
- We can debounce the onChange and change the value from outside

Add link button + fix toggle

---

containers/layouts/ComposerModeRadios.js
containers/layouts/DraftTypeSelect.js
containers/layouts/LayoutsSection.js
containers/layouts/RadioCards.js
containers/layouts/ShowMovedSelect.js
containers/layouts/TextDirectionSelect.js
containers/layouts/ViewLayoutRadios.js
containers/layouts/ViewModeRadios.js

Add layouts

---

components/sidebar/SubSidebar.js
components/sidebar/SubSidebar.test.js

Add SubSidebar component

---

components/alert/Alert.js

Add mode standard for Alert

---

components/input/DateInput.js
containers/logs/LogsSection.js
index.js
package.json
styles/index.scss

Fix #37 - Add DateInput component

---

containers/invoices/InvoiceActions.js
containers/invoices/InvoiceModal.js
containers/invoices/PreviewInvoiceModal.js

Preview PDF invoice in modal
Reference: https://github.com/ProtonMail/protonmail-settings/issues/27

Use native PDF support to preview an invoice

---

components/modal/Confirm.js
components/modal/Inner.js
components/modal/Input.js
components/modal/PreviewPDFModal.js
containers/account/DeleteAccountModal.js
containers/addresses/AddressModal.js
containers/addresses/EditAddressModal.js
containers/domains/CatchAllModal.js
containers/domains/DomainModal.js
containers/general/ShortcutsModal.js
containers/invoices/InvoiceTextModal.js
containers/invoices/PayInvoiceModal.js
containers/members/EditMemberModal.js
containers/members/MemberModal.js
containers/password/AskPasswordModal.js
containers/payments/DonateModal.js
containers/payments/EditCardModal.js
containers/support/BugModal.js
index.js

New container added recently in the design-system, so we need to wrap the body with `InnerModal` component.
```
<div class="pm-modalContentInner">{children}</div>
```

Update all modal to use InnerModal

---

components/input/DateInput.js
components/input/RichTextEditor.js
components/select/TimeSelect.js
containers/autoReply/AutoReplyForm/AutoReplyForm.js
containers/autoReply/AutoReplyForm/fields/DaysOfWeekField.js
containers/autoReply/AutoReplyForm/fields/DurationField.js
containers/autoReply/AutoReplyForm/fields/EndDateField.js
containers/autoReply/AutoReplyForm/fields/EndDayOfMonthField.js
containers/autoReply/AutoReplyForm/fields/EndDayOfWeekField.js
containers/autoReply/AutoReplyForm/fields/EndTimeField.js
containers/autoReply/AutoReplyForm/fields/StartDateField.js
containers/autoReply/AutoReplyForm/fields/StartDayOfMonthField.js
containers/autoReply/AutoReplyForm/fields/StartDayOfWeekField.js
containers/autoReply/AutoReplyForm/fields/StartTimeField.js
containers/autoReply/AutoReplyForm/fields/TimeZoneField.js
containers/autoReply/AutoReplyForm/useAutoReplyForm.js
containers/autoReply/AutoReplyModal.js
containers/autoReply/AutoReplySection.js
containers/autoReply/AutoReplyTemplate.js
containers/autoReply/AutoReplyToggle.js
containers/autoReply/InfoLine.js
containers/autoReply/utils.js
index.js
package.json

Auto-reply functionality for: https://github.com/ProtonMail/protonmail-settings/issues/10
**Related PRs:**
- `protonmail-settings`: https://github.com/ProtonMail/protonmail-settings/pull/29
- `design-system`: https://github.com/ProtonMail/design-system/pull/114 ✅
- `proton-shared`: https://github.com/ProtonMail/proton-shared/pull/16 ✅

Components for auto-reply feature

---

containers/messages/ShowMovedToggle.js

Closes #72
https://github.com/ProtonMail/proton-shared/pull/19 must be approved first.

Update ShowMovedToggle component

---

containers/addresses/AddressModal.js
containers/addresses/AddressesSection.js
containers/addresses/AddressesTable.js
containers/addresses/AddressesToolbar.js
containers/addresses/DomainsSelect.js
containers/addresses/PMSignatureToggle.js
containers/members/MembersSection.js
containers/payments/BillingSection.js
containers/payments/subscription/FeaturesList.js
containers/search/SearchSection.js
hooks/usePermissions.js

This section was not working for free user.
Need lib to re-order addresses for the current user.

WIP - Refactoring addresses section

---

components/editableText/EditableText.js
components/text/Preformatted.js
index.js

Components that I needed in admin-web-panel, but that might be useful for other projects.
Editing:
Not editing:
Preformatted:

Editable text and preformatted text components

---

containers/apps/ProtonMailAppsSection.js
containers/invoices/InvoiceState.js
containers/login/LoginContainer.js
containers/logs/LogsSection.js
containers/logs/LogsTable.js
containers/members/MemberRole.js
containers/payments/BillingSection.js
containers/payments/CreditsModal.js
containers/payments/CycleDiscountBadge.js
containers/payments/subscription/CustomPlusSection.js
containers/payments/subscription/CustomProfessionalSection.js
containers/payments/subscription/CustomVPNSection.js
containers/payments/subscription/PaymentDetails.js
containers/payments/subscription/SubscriptionDetails.js
containers/payments/subscription/SubscriptionSection.js
containers/sessions/SessionsSection.js

I checked all cases where `t'string to be translated'` appears in this repo. Most of them are inside components already. I moved all the rest. Hopefully I didn't miss any case.
I didn't touch the files inside `containers/keys` since @mmso was working on them
Closes #77

Move string translations inside components

---

styles/index.scss

Include new CSS style from design-system for having a nice progress bar

add pm-progress-contact style

---

components/button/Copy.js
components/button/IconButton.js
components/editableText/EditableText.js
components/pagination/Pagination.js
containers/autoReply/AutoReplyModal.js
containers/layouts/ToolbarsSection.js

Button with `pm-button--for-icon` class added and `icon` prop as a button prop.

Icon button to use for buttons containing only icons without text

---

components/modal/FormModal.js
components/modal/PreviewPDFModal.js
containers/invoices/InvoiceActions.js
containers/invoices/InvoicesSection.js

Remove the extra state as we can give to the modal the URL.

Show invoice inside PreviewInvoiceModal

---

containers/general/ShortcutsModal.js

Fix #43 ~ Remove submit button from the modal

---

components/orderable/OrderableHandle.js
components/orderable/index.js
components/orderableTable/OrderableTable.js
components/orderableTable/OrderableTableRow.js

Ref: https://github.com/ProtonMail/proton-contacts/pull/32#issuecomment-514175862

OrderableTable ordering using icon only

---

containers/app/StandardPrivateApp.js
containers/eventManager/ModelListener.js
hooks/helpers/createModelHook.js
hooks/useCachedModelResult.js
hooks/useOrganization.js
hooks/usePlans.js
hooks/useSubscription.js
index.js

* Move to component subscription for event manager
* Update useCachedModelResult to pass cache

Fix contacts

---

components/modal/SimpleModal.js
containers/payments/PlansSection.js
containers/payments/subscription/UpgradeModal.js
containers/payments/subscription/UpgradeModal.scss
index.js

Fix https://github.com/ProtonMail/react-components/issues/137

Add upgrade modal

---

containers/payments/subscription/FeaturesList.js
containers/payments/subscription/SubscriptionModal.js
containers/payments/subscription/SubscriptionModal.scss
containers/payments/subscription/Thanks.js
containers/payments/subscription/UpgradeModal.js

Fix https://github.com/ProtonMail/protonmail-settings/issues/82

Add design for Thanks section

---

containers/addresses/AddressesWithUser.js

Fix: https://github.com/ProtonMail/protonmail-settings/issues/36

Order addresses

---

containers/organization/ChangeOrganizationKeysModal.js
containers/organization/ReactivateOrganizationKeysModal.js
hooks/useOrganizationKey.js

Fix https://github.com/ProtonMail/protonmail-settings/issues/86

Fix organization keys reset

---

containers/layouts/LayoutsSection.js

Fix: https://github.com/ProtonMail/protonmail-settings/issues/70

Disable sticky labels when not in conversation mode

---

containers/addresses/AddressesWithMembers.js

Fix: https://github.com/ProtonMail/protonmail-settings/issues/36

Order addresses when selected user selected itself

---

hooks/useSubscription.js

Ensure the user is an admin to get the subscription
Fix https://github.com/ProtonMail/protonmail-settings/issues/83

Fix subscription get

---

containers/messages/EmbeddedToggle.js
containers/messages/RemoteToggle.js
containers/messages/RequestLinkConfirmationToggle.js
containers/messages/ShowMovedToggle.js

Fix https://github.com/ProtonMail/protonmail-settings/issues/87

Review toggles in messages section

---

containers/addresses/AddressesWithMembers.js
containers/members/MemberAddresses.js
containers/members/MembersSection.js

Fix: https://github.com/ProtonMail/protonmail-settings/issues/72

List addresses of preselected user if there is one

---

containers/filters/AddFilterModal.js
containers/filters/editor/Conditions.js
containers/filters/editor/EditConditionValue.js
containers/filters/editor/LabelActions.js

Fixes: https://github.com/ProtonMail/protonmail-settings/issues/88
And additional bug I noticed, where filter condition would not be saved after editing (only local state was updated, not the model).

Fix filter condition editing and deleting

---

components/dropdown/DropdownCaret.js
containers/heading/UserDropdown.js
containers/heading/UserDropdownButton.js
containers/payments/DonateModal.js
index.js

Fix: https://github.com/ProtonMail/protonmail-settings/issues/69
Design is the same as current version in Angular 4 project (discussed with Nico).
Fixed DonateModal width & props validation.

Add UserDropdown

---

components/logo/MailLogo.js

Use new classes from design-system (https://design-system-beta.netlify.com/colors/)

Add color to plan in main Logo

---

containers/heading/UpgradeButton.js
index.js

The popup opens on /settings/subscription page if the user is on the free plan (PlansSection component), so we simply redirect him to that page and let it handle everything (same behavior is on Angular 4 project).

Add UpgradeButton (#152)

---

components/orderableTable/OrderableTable.scss
components/orderableTable/OrderableTableHeader.js
components/table/TableHeader.js
containers/labels/LabelSortableItem.js
containers/labels/LabelSortableList.js
containers/labels/LabelsSection.js

Fix: https://github.com/ProtonMail/protonmail-settings/issues/89

Orderable folders & labels

---

containers/addresses/PmMePanel.js

Don't request members if the user is not an admin
Fix https://github.com/ProtonMail/protonmail-settings/issues/83

Fix https://github.com/ProtonMail/protonmail-settings/issues/83

---

index.js

Export useUserVPN hook

---

components/input/TelInput.js
containers/apps/ProtonVPNAppsSection.js
containers/vpn/OpenVPNAccountSection/OpenVPNAccountSection.js
containers/vpn/OpenVPNConfigurationSection/OpenVPNConfigurationSection.js
containers/vpn/ProtonVPNClientsSection/ProtonVPNClientsSection.js
containers/vpn/ProtonVPNCredentialsSection/ProtonVPNCredentialsSection.js
containers/vpn/ProtonVPNResourcesSection/ProtonVPNResourcesSection.js
index.js

 Resources and credentials sections

---

containers/account/NewsCheckboxes.js

Delong needs to validate wording.

Handle new flag for business news

---

components/orderableTable/OrderableTableBody.js
containers/addresses/AddressesWithUser.js
containers/addresses/helper.js

Fixes: https://github.com/ProtonMail/protonmail-settings/issues/99

Prevent disabling default addresses

---

components/container/SimpleTabs.js
components/container/Tabs.js

@nico3333fr will add the appropriate style on design-system.

Add Tabs component

---

containers/heading/UserDropdown.js

**Summary**
Adds data-cy-* attributes needed for logout command in e2e tests.

Add test attributes needed for logout.

---

containers/members/MemberStorageSelector.js
containers/members/MemberVPNSelector.js

Fix https://github.com/ProtonMail/protonmail-settings/issues/100

Review ranges for VPN and Storage

---

components/dropdown/Dropdown.js
components/dropdown/SimpleDropdown.js
components/link/Href.js
components/pagination/Pagination.js
components/progress/CircularProgress.js
components/progress/CircularProgress.scss
containers/app/AppsSidebar.js
containers/app/StorageSpaceStatus.js
containers/sidebar/StorageSpaceStatus.js
index.js

Storage space status & CircularProgress component (#179)

---

containers/rightToLeft/Provider.js

Fix invalid argument on edge

---

containers/payments/BillingSection.js
containers/vpn/OpenVPNConfigurationSection/OpenVPNConfigurationSection.js
containers/vpn/OpenVPNConfigurationSection/ServerConfigs.js

Typical javascript error...
Fixes: https://github.com/ProtonMail/protonvpn-settings/issues/22
Fixes: https://github.com/ProtonMail/protonvpn-settings/issues/37

Fix download permissions for openvpn config

---

containers/paymentMethods/PaymentMethodsSection.js

In https://github.com/ProtonMail/react-components/pull/207 I missed to commit [this change](https://github.com/ProtonMail/react-components/pull/208/commits/8b100ea9dbf74e3ea6c9f81cb580d07e1cfa7dd0).

Missing fix from previous PR

---

containers/app/ErrorBoundary.js

Trace exception from ErrorBoundary with Sentry

---

containers/heading/UserDropdownButton.js

To harmonize this component with Angular/Design System and as requested by designers, the user drop down has been updated:
Normal 
Hover 
Opened

Fix user dropdown design

---

containers/notification/EmailSection.js

Spotted by Keven: alignment was not correct on emailSection component:
Before:
- made it vertically aligned using helpers
Snapshot after fix:

Fix emailSection alignment

---

containers/heading/UserDropdownButton.js

Fix: https://github.com/ProtonMail/react-components/issues/199

Fix color in user dropdown button (#199)

---

components/sidebar/NavItem.js

- added same classes as on Angular/Design system to be able to style projects the same way.

Fix navigation icon display

---

containers/app/AppsSidebar.js

- added missing classes for design and centering:
Before:
After:

Fix aside icon layout

---

components/modal/Content.js
containers/app/ProtonApp.js
containers/app/StandardPrivateApp.js
containers/domains/DomainModal.js
containers/modals/Children.js
containers/modals/Container.js
containers/modals/Provider.js

Fixes: #119 
Also clean some console.errors

Reset modals when navigating

---

components/input/PasswordInput.js

I just need this class to fix https://github.com/ProtonMail/design-system/issues/210 :)

Add class on password revealer container

---

containers/app/StandardPrivateApp.js
containers/eventManager/EventNotices.js

Fix #232
NOTE: Uses localStorage instead of cookies (as it's done in the angular app)

Fix #232 - Add support for Notices from event manager

---

containers/login/AbuseModal.js
containers/login/LoginForm.js

Add abuse modal on login

---

containers/account/DeleteAccountModal.js

To make the delete button red (`<ErrorButton />` component), we need to add a new prop for `FormModal` or use `footer` prop to define custom buttons. I chose the second option.
Fix https://github.com/ProtonMail/proton-vpn-settings/issues/85

Make submit button red for delete modal

---

containers/filters/editor/AddConditionValue.js
containers/filters/editor/EditConditionValue.js

Conditions buttons were cropped:
- added `flex-item-noshrink` to buttons
Once fixed:

Fix condition button display

---

containers/invoices/PayInvoiceModal.js
containers/payments/CreditsModal.js
containers/payments/DonateModal.js
containers/payments/EditCardModal.js
containers/payments/PayPal.js
containers/payments/PaymentVerificationModal.js
containers/payments/paymentTokenHelper.js
containers/payments/subscription/SubscriptionModal.js
index.js

Use a modal to handle token process

---

components/logo/MainLogo.js

To make main logo able to disappear on mobiles (with class `nomobile`):

Fix - rwd main logo

---

components/sidebar/Sidebar.js

Added logo in nav container. Only for mobile

Add logo only on mobile in sidebar container

---

containers/vpn/OpenVPNAccountSection/OpenVPNAccountSection.js

Component was a bit broken on med/low resolutions:
Tablets (button shrinks):
Mobiles (alignments):
- added some mobile helpers for proper alignments
- made button not "shrinkable"
Fix applied:
On tablets:
On mobiles:

Fix RWD OpenVPN account section

---

components/input/RadioGroup.js
containers/vpn/OpenVPNConfigurationSection/OpenVPNConfigurationSection.js

- Allow radios to wrap and added some margin-bottom
Fix applied:

Fix - rwd for radios groups

---

components/sidebar/Hamburger.js

Fixed size and color of burger.

Fix hamburger size/color

---

containers/invoices/InvoicesSection.js

- added min-width helper for correct display of invoice table

Fix - min width for invoice table

---

components/badge/Badge.js

Added primary-colored badges
Needed for VPN signup

Fix badges

---

containers/vpn/OpenVPNConfigurationSection/ConfigsTable.js
containers/vpn/OpenVPNConfigurationSection/OpenVPNConfigurationSection.js

Fix https://github.com/ProtonMail/proton-vpn-settings/issues/115

Fixes on downloads page

---

components/modal/Dialog.js
components/modal/FormModal.js
components/modal/Overlay.js
containers/modals/Container.js

Fix https://github.com/ProtonMail/design-system/issues/217
https://github.com/ProtonMail/design-system/pull/220

Position modals with flex instead of 3d transformation

---

containers/payments/subscription/SubscriptionModal.js

- updated sentence
Fixes: https://github.com/ProtonMail/proton-vpn-settings/issues/174

Fix TOS naming

---

components/input/IntlTelInput.js
components/input/IntlTelInput.scss
index.js
package.json

Fixes #250 
I haven't touched the formatting as I'm not sure how it should work. Currently it functions as simple text input with placeholder as an example.
Also the design is not defined as well, so I tried to make it look at least decent for now.
Needs https://github.com/ProtonMail/design-system/pull/219

IntlTelInput component

---

containers/account/DeleteAccountModal.js

Fix https://github.com/ProtonMail/proton-vpn-settings/issues/209

Report bug first

---

containers/account/DeleteAccountModal.js

Fix https://github.com/ProtonMail/proton-vpn-settings/issues/209

Use noemail@example.com if nothing entered

---

containers/payments/paymentTokenHelper.js

Fix secure path

---

containers/payments/Bitcoin.js

We still display error notification and that's fine.

Display error for bitcoin in the view

---

containers/vpn/OpenVPNAccountSection/OpenVPNAccountSection.js

Fix https://github.com/ProtonMail/proton-vpn-settings/issues/233

Add toggle for OpenVPN password

---

components/modal/FormModal.js
containers/payments/subscription/SubscriptionModal.js
containers/payments/subscription/Thanks.js

Fix https://github.com/ProtonMail/proton-vpn-settings/issues/55

Remove "thank you" footer in subscription modal

---

containers/app/CompatibilityCheck.js

Add `title` on  compatibility check page when needed.

Add title on compatibility check page

---

containers/app/CompatibilityCheck.js
containers/app/ProtonApp.js

Fix unsupported kb url

---

containers/account/DeleteAccountModal.js

Fix https://github.com/ProtonMail/proton-vpn-settings/issues/252

Require email on delete

---

containers/sessions/SessionsSection.js

**Summary**
Adds client name for the new ProtonVPN web app.
**Before**
**After**

Add the new ProtonVPN web app

---

containers/resetPassword/DangerVerificationForm.js

Fix https://github.com/ProtonMail/proton-vpn-settings/issues/260

Prevent default was missing from danger form

---

containers/account/EnableTwoFactorModal.js
containers/account/TwoFactorSection.js

Fixes https://github.com/ProtonMail/proton-vpn-settings/issues/263

Use 2FA VPN link if coming from VPN app

---

components/input/Input.js
containers/paymentMethods/PaymentMethodActions.js
containers/payments/Card.js
containers/payments/CardNumberInput.js
containers/payments/ExpInput.js
containers/payments/cardValidator.js
containers/payments/getDefaultCard.js
containers/payments/useCard.js

Review form structure and exp field to have a better auto-fill coverage by browsers and password managers.
- The Edge auto-fill doesn't work well and that's OK.
- 1Password works fine tested on 3 machines.
- Dashlane has issue with `<select>`.

Review card form structure

---

components/input/Input.js
components/input/PasswordInput.js
containers/payments/CardNumberInput.js

- Wrap input + icon if needed
- Insert icon to the proper place

Add icon prop to Input

---

containers/payments/PaymentVerificationImage.js
containers/payments/PaymentVerificationModal.js
containers/payments/paymentTokenHelper.js

Display verified bank images

---

containers/payments/subscription/SubscriptionModal.js
containers/payments/subscription/Upgrading.js
hooks/useStep.js

Fix https://github.com/ProtonMail/proton-vpn-settings/issues/284

Add upgrading step in subscription flow

---

containers/overview/SummarySection.js

Fixes https://github.com/ProtonMail/proton-mail-settings/issues/130

Show recovery email if it is set

---

containers/paymentMethods/PaymentMethodsSelect.js

`methods` is an Array
Fix https://github.com/ProtonMail/proton-vpn-settings/issues/289

Hotfix - methods is changing but not the length

---

containers/vpn/OpenVPNConfigurationSection/ConfigsTable.js

Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/8

Use UK instead of GB when downloading configs

---

containers/payments/EditCardModal.js
containers/payments/PaymentVerificationModal.js
containers/payments/paymentTokenHelper.js

Fix https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/4

Add card mode for payment verification modal

---

containers/vpn/ProtonVPNClientsSection/ProtonVPNClientsSection.js

Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/13

Add UTM tags to Google Play link

---

containers/filters/FilterItemRow.js
containers/filters/FiltersSection.js
containers/filters/SortableList.js

Fixes https://github.com/ProtonMail/proton-mail-settings/issues/138

Fix filter sorting

---

components/logo/MainLogo.js

Add @type any to MainLogo component

---

containers/paymentMethods/PaymentMethodsSection.js

Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/17

Hide paypal method if added

---

containers/keys/addKey/AddKeyModal.js
containers/keys/deleteKey/DeleteKeyModal.js

- Update the text shown in alert on Delete key step, fixes issue #320 
From `We are now deleting the key for your address.`
To: `The key for your address is now being deleted.`

Update the text for delete key press in DeleteKeyModal

---

containers/app/AppsSidebar.js

The app icons are different from sidebar icons!
See https://github.com/ProtonMail/design-system/pull/239

Correct icon update

---

styles/index.scss

Added `pm-cursors` fragment from Design system (a set of helpers to manage cursor styles).

Add cursors fragment

---

containers/payments/PayPal.js
containers/payments/PaymentVerificationModal.js
containers/payments/paymentTokenHelper.js

type: Original type used to generate the token (card, paypal, paypal-credit)

Pass payment method type accros payment flow

---

containers/sidebar/StorageSpaceStatus.js

- updated icon design - provided  by design

Fix storage space icon

---

containers/addresses/EditAddressModal.js

- added a modifier to make the Rich Text Edition full width
- also fixed alignement issue

Fix - signature rich edit block width

---

components/button/Copy.test.js

Currently CircleCI fails because this test is not passing since the structure of the component changed in https://github.com/ProtonMail/react-components/commit/df6443d079d02544ab3ceb40561ef61167ac688a

Fix Copy button test

---

containers/login/SignInLayout.js

Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/26

Remove the https:// part from back link text

---

components/sidebar/MobileNavServices.js
hooks/useActiveBreakpoint.js

We were forgetting about `tinymobile`

New changes to useActiveBreakpoints hook

---

containers/account/ChangePasswordModal.js

Re-render password inputs when phase changes

Fix https://github.com/ProtonMail/proton-mail-settings/issues/180

---

containers/themes/ThemesSection.js

Fix https://github.com/ProtonMail/proton-mail-settings/issues/186

Add confirm modal to switch team from custom

---

containers/heading/UserDropdownButton.js

Address cut of due to line-height
- added some classes in Design system and revamped line-height management (harmonized with React/Design system, was the mess)

Fix #9219 - address cut off

---

containers/filters/SortableList.js

Fixes https://github.com/ProtonMail/proton-mail-settings/issues/138

Pass props to FilterSortableList component

---

components/miniCalendar/MiniCalendar.js
components/miniCalendar/MonthDays.js
components/miniCalendar/WeekNumbers.js

- reordered/re-aligned buttons
- resize cells
- fix rounded issue for current day
- styled markers properly
Fixes #423

Fix #423 - minicalendar layout

---

containers/payments/LossLoyaltyModal.js
containers/payments/PlansSection.js
index.ts

All loyal users will receive a bonus on their paid subscription. We need to display a modal to inform them about this bonus when they try to unsubscribe.

Display loyalty modal when unsubscribe

---

components/modal/Header.js

Icon was wrong, but nobody noticed. 🎉 
- added correct icon
- added text for aâAÂÄccessibility
- fixed positionning in design system
Fixes #309

Fix modal icon + positionning

---

components/miniCalendar/MonthDays.js
components/miniCalendar/WeekNumbers.js

- added some modifiers to help styling range selection
- added data attribute to help styling range selection
Fixes #89
@mmso  🙏 : when you click on only one day without creating a range, there is no aria-pressed="true", which makes styles fail.

Feat #89 - range selection design

---

containers/filters/FilterConditionValues.js
containers/filters/editor/Actions.js
containers/filters/editor/AddConditionValue.js
containers/filters/editor/Conditions.js
containers/filters/editor/EditConditionValue.js

Fix: https://github.com/ProtonMail/proton-mail-settings/issues/236
For the first point about deleting a condition. What I seen is that the model data in React was ok but some `select` was not displaying what they should because of the tracking of conditions based on the array index. So I added a computed id on conditions and it should be better.
For the last point about adding value, waiting for feedback.

Improvements on filter modal

---

components/input/Input.js
components/input/TextArea.js
components/input/useInput.js
components/select/Select.js

Add isSubmitted flag to inputs so that errors can be displayed without the inputs having to be dirty.
It would still be up to each form to handle this.

Submitted flag to inputs

---

components/price/Price.js

Fix #248 - Display float price with 2 digit at least

---

containers/payments/BillingSection.js
containers/payments/DiscountBadge.js
containers/payments/subscription/SubscriptionDetails.js
containers/payments/subscription/SubscriptionSection.js
containers/sidebar/StorageSpaceStatus.js

- Includes discount badge logic in one component: `<Discountbadge />`
Design: https://zpl.io/25owv68

Revamp billing details

---

containers/payments/CycleSelector.js

Fix https://github.com/ProtonMail/proton-mail-settings/issues/250

Display 2 YEAR also during / after BF period

---

components/input/DateInput.js
components/input/TimeInput.js
components/miniCalendar/MiniCalendar.js
components/miniCalendar/MonthDays.js

Add min max to date and time inputs

---

components/sidebar/SubSidebar.js

Just a tiny fix for darkmode.
- removed class, styles have been moved to Design System here: https://github.com/ProtonMail/design-system/commit/9aac462ba03ff595e50dc6e17601d2555147ec21

Fix - subnav for darkmode

---

containers/payments/subscription/SubscriptionSection.js

Review subscription section

---

containers/heading/UserDropdown.js

I needed to add a class on user drop down to fix some points for Dark mode/styling, etc.
- added `dropDown-link` class on it, styles are already ready in Design system.

Fix - user Drop Down link classes

---

containers/login/SignInLayout.js

Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpncom/issues/365

Fix links in signin layout

---

components/countdown/Countdown.js
containers/payments/subscription/BlackFridayModal.js
containers/payments/subscription/BlackFridayModal.scss
index.ts

- New component added: `Countdown`
Fix https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/51
Manager Delong
Test server https://vpnsettings.protonmail.blue (`blue` API)

Improve Black Friday

---

components/table/TableHeader.tsx
containers/api/ApiProvider.js

Allows to get a response stream, currently required to be able to show progress when downloading files (proton-drive)
Maybe requires polyfill for ReadableStream.

Add stream support to api function

---

components/modal/Dialog.js
containers/modals/Container.js
containers/modals/Provider.js
containers/modals/manager.js

Remove the behavior that allow the user to click outside the modal to have it closed
Also add support for customly rendering a modal

Fix https://github.com/ProtonMail/react-components/issues/481

---

containers/app/StandardPreload.js
containers/app/StandardPrivateApp.js
containers/app/StandardPublicApp.js

requires: https://github.com/ProtonMail/proton-shared/pull/87 in proton-shared

Allow passing configuration to openpgp per-project

---

containers/app/AppsSidebar.js

Fix - aside icon order

---

components/color/ColorSelector.scss

Fix - dark mode circle

---

containers/paymentMethods/PaymentMethodDetails.js

- just replaced `bg-global-light` by `bg-global-highlight` (dark mode friendly alias for this class)

Fix - payment method info

---

components/image/RemoteImage.js

Related to https://github.com/ProtonMail/proton-contacts/issues/194

images should have by default a no-referrer policy

---

components/image/RemoteImage.js

React wants referrerPolicy instead of referrerpolicy as a prop

Fix typo in #513

---

containers/addresses/CreateMissingKeysAddressModal.js

Update missing keys submit button text to 'Done' or 'Close' in case of failure

Fix missing keys submit text

---

containers/vpn/OpenVPNConfigurationSection/ConfigsTable.js

Fixes https://gitlab.protontech.ch/ProtonVPN/web/protonvpn-settings/issues/22

Show "Server is down" sign only if all servers in specific country are down

---

containers/payments/subscription/CustomVPNSection.js

- updated `bg-global-light` classes to `bg-global-highlight` (same but dark-mode friendly version)

Fix - add dark-mode friendly classes

---

components/color/ColorSelector.js
components/dropdown/DropdownActions.js
components/orderableTable/OrderableTableRow.js
containers/labels/ActionsLabel.js
containers/labels/ActionsLabelToolbar.js
containers/labels/LabelSortableItem.js
containers/labels/LabelSortableList.js
containers/labels/NewLabelForm.js

Summary:
This will add various test ids for items under  folders/labels section in settings page.

Add test id for various items in folders/labels section

---

containers/themes/ThemeInjector.js

This will be convenient for handling dark mode purely from css

add dummy css class in the body for detecting the dark mode

---

containers/organization/OrganizationPasswordSection.js
containers/organization/OrganizationSection.js

Buttons were badly displayed on mobile. (no margin, etc.)
- added some margin/fix spacing on mobile

Fix - mobile organisation button display

---

containers/filters/editor/Sieve.js
containers/themes/ThemesSection.js

Fix one of the issues in https://github.com/ProtonMail/proton-mail-settings/issues/270

change theme for sieve editor in dark mode

---

components/input/DateInput.tsx
containers/autoReply/AutoReplyForm/fields/DateField.js

**EN-US Locale:**
**EN-GB locale:**
**EN-GB selected:**
This is a breaking change and has to be announced when merged

Allow date input to have empty value

---

components/button/Copy.js
components/icon/RoundedIcon.js
containers/domains/DKIMSection.js
containers/domains/DMARCSection.js
containers/domains/DomainModal.js
containers/domains/DomainSection.js
containers/domains/GenerateKeyModal.js

Manager: Kamila
Jira issue: https://jira.protontech.ch/browse/MAILFE-155

DKIM rotation phase 1
